development: &default
  adapter: postgresql
  encoding: utf8
  database: sample_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

staging:
  <<: *default
  database: sample_staging

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample_production
